### PR TITLE
Update zh.json

### PR DESCRIPTION
**Pull request by dongfangbotao1**

### CODE REVIEW

**Comment by dongfangbotao1** [comment]
I should have deleted it, but I don't know.I should have deleted it, but I don't know if I really deleted it.I should have deleted it, but I don't know if I really deleted it. I don't know how to use github. If I really didn't delete it, please help me delete it.I should have been deleted, but I don’t know if I really delete it. I don’t know how github is used. If I do n’t delete it, please help me delete it, or send me a tutorial for me.I should have been deleted, but I don’t know if I really delete it. I don’t know how GitHub uses it. If I really do n’t delete it, please help me delete it, or send me a tutorial.

**Comment by dongfangbotao1** [comment]
我完全删掉了我的库，这下应该没问题了

**Comment by dongfangbotao1** [comment]
我已经全部都删了，请你们看看我删的对不对



---Original---
From: ***@***.***&gt;
Date: Sun, Jul 31, 2022 20:27 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [arcxingye/EatKano] Update zh.json (PR #164)




 
Closed #164.

**Comment by kifuan** [comment]
大可不必

**Comment by kifuan** [comment]
你自己玩吧，别点Pull Request

**Comment by dongfangbotao1** [comment]
OK, thank you.



---Original---
From: ***@***.***&gt;
Date: Sun, Jul 31, 2022 21:11 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [arcxingye/EatKano] Update zh.json (PR #164)




 
你自己玩吧，别点Pull Request

**Comment by dongfangbotao1** [comment]
I'm sorry. Just a moment.



---Original---
From: ***@***.***&gt;
Date: Sun, Jul 31, 2022 20:27 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [arcxingye/EatKano] Update zh.json (PR #164)




 
Closed #164.

**Pull request closed without merging**
